// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"mingyang-admin-simple-admin-file/ent/apk"
	"mingyang-admin-simple-admin-file/ent/cloudfile"
	"mingyang-admin-simple-admin-file/ent/cloudfiletag"
	"mingyang-admin-simple-admin-file/ent/file"
	"mingyang-admin-simple-admin-file/ent/filetag"
	"mingyang-admin-simple-admin-file/ent/schema"
	"mingyang-admin-simple-admin-file/ent/storageprovider"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apkMixin := schema.Apk{}.Mixin()
	apkMixinFields0 := apkMixin[0].Fields()
	_ = apkMixinFields0
	apkMixinFields1 := apkMixin[1].Fields()
	_ = apkMixinFields1
	apkMixinFields2 := apkMixin[2].Fields()
	_ = apkMixinFields2
	apkFields := schema.Apk{}.Fields()
	_ = apkFields
	// apkDescCreatedAt is the schema descriptor for created_at field.
	apkDescCreatedAt := apkMixinFields0[1].Descriptor()
	// apk.DefaultCreatedAt holds the default value on creation for the created_at field.
	apk.DefaultCreatedAt = apkDescCreatedAt.Default.(func() time.Time)
	// apkDescUpdatedAt is the schema descriptor for updated_at field.
	apkDescUpdatedAt := apkMixinFields0[2].Descriptor()
	// apk.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apk.DefaultUpdatedAt = apkDescUpdatedAt.Default.(func() time.Time)
	// apk.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apk.UpdateDefaultUpdatedAt = apkDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apkDescStatus is the schema descriptor for status field.
	apkDescStatus := apkMixinFields1[0].Descriptor()
	// apk.DefaultStatus holds the default value on creation for the status field.
	apk.DefaultStatus = apkDescStatus.Default.(uint8)
	// apkDescTenantID is the schema descriptor for tenant_id field.
	apkDescTenantID := apkMixinFields2[0].Descriptor()
	// apk.DefaultTenantID holds the default value on creation for the tenant_id field.
	apk.DefaultTenantID = apkDescTenantID.Default.(uint64)
	// apkDescFileSize is the schema descriptor for file_size field.
	apkDescFileSize := apkFields[3].Descriptor()
	// apk.DefaultFileSize holds the default value on creation for the file_size field.
	apk.DefaultFileSize = apkDescFileSize.Default.(uint64)
	// apkDescIsForceUpdate is the schema descriptor for is_force_update field.
	apkDescIsForceUpdate := apkFields[12].Descriptor()
	// apk.DefaultIsForceUpdate holds the default value on creation for the is_force_update field.
	apk.DefaultIsForceUpdate = apkDescIsForceUpdate.Default.(bool)
	// apkDescDownloadCount is the schema descriptor for download_count field.
	apkDescDownloadCount := apkFields[13].Descriptor()
	// apk.DefaultDownloadCount holds the default value on creation for the download_count field.
	apk.DefaultDownloadCount = apkDescDownloadCount.Default.(int64)
	cloudfileMixin := schema.CloudFile{}.Mixin()
	cloudfile.Policy = privacy.NewPolicies(schema.CloudFile{})
	cloudfile.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := cloudfile.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	cloudfileHooks := schema.CloudFile{}.Hooks()

	cloudfile.Hooks[1] = cloudfileHooks[0]
	cloudfileMixinFields0 := cloudfileMixin[0].Fields()
	_ = cloudfileMixinFields0
	cloudfileMixinFields1 := cloudfileMixin[1].Fields()
	_ = cloudfileMixinFields1
	cloudfileMixinFields2 := cloudfileMixin[2].Fields()
	_ = cloudfileMixinFields2
	cloudfileFields := schema.CloudFile{}.Fields()
	_ = cloudfileFields
	// cloudfileDescCreatedAt is the schema descriptor for created_at field.
	cloudfileDescCreatedAt := cloudfileMixinFields0[1].Descriptor()
	// cloudfile.DefaultCreatedAt holds the default value on creation for the created_at field.
	cloudfile.DefaultCreatedAt = cloudfileDescCreatedAt.Default.(func() time.Time)
	// cloudfileDescUpdatedAt is the schema descriptor for updated_at field.
	cloudfileDescUpdatedAt := cloudfileMixinFields0[2].Descriptor()
	// cloudfile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cloudfile.DefaultUpdatedAt = cloudfileDescUpdatedAt.Default.(func() time.Time)
	// cloudfile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cloudfile.UpdateDefaultUpdatedAt = cloudfileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cloudfileDescState is the schema descriptor for state field.
	cloudfileDescState := cloudfileMixinFields1[0].Descriptor()
	// cloudfile.DefaultState holds the default value on creation for the state field.
	cloudfile.DefaultState = cloudfileDescState.Default.(bool)
	// cloudfileDescTenantID is the schema descriptor for tenant_id field.
	cloudfileDescTenantID := cloudfileMixinFields2[0].Descriptor()
	// cloudfile.DefaultTenantID holds the default value on creation for the tenant_id field.
	cloudfile.DefaultTenantID = cloudfileDescTenantID.Default.(uint64)
	cloudfiletagMixin := schema.CloudFileTag{}.Mixin()
	cloudfiletag.Policy = privacy.NewPolicies(schema.CloudFileTag{})
	cloudfiletag.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := cloudfiletag.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	cloudfiletagHooks := schema.CloudFileTag{}.Hooks()

	cloudfiletag.Hooks[1] = cloudfiletagHooks[0]
	cloudfiletagMixinFields0 := cloudfiletagMixin[0].Fields()
	_ = cloudfiletagMixinFields0
	cloudfiletagMixinFields1 := cloudfiletagMixin[1].Fields()
	_ = cloudfiletagMixinFields1
	cloudfiletagMixinFields2 := cloudfiletagMixin[2].Fields()
	_ = cloudfiletagMixinFields2
	cloudfiletagFields := schema.CloudFileTag{}.Fields()
	_ = cloudfiletagFields
	// cloudfiletagDescCreatedAt is the schema descriptor for created_at field.
	cloudfiletagDescCreatedAt := cloudfiletagMixinFields0[1].Descriptor()
	// cloudfiletag.DefaultCreatedAt holds the default value on creation for the created_at field.
	cloudfiletag.DefaultCreatedAt = cloudfiletagDescCreatedAt.Default.(func() time.Time)
	// cloudfiletagDescUpdatedAt is the schema descriptor for updated_at field.
	cloudfiletagDescUpdatedAt := cloudfiletagMixinFields0[2].Descriptor()
	// cloudfiletag.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cloudfiletag.DefaultUpdatedAt = cloudfiletagDescUpdatedAt.Default.(func() time.Time)
	// cloudfiletag.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cloudfiletag.UpdateDefaultUpdatedAt = cloudfiletagDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cloudfiletagDescStatus is the schema descriptor for status field.
	cloudfiletagDescStatus := cloudfiletagMixinFields1[0].Descriptor()
	// cloudfiletag.DefaultStatus holds the default value on creation for the status field.
	cloudfiletag.DefaultStatus = cloudfiletagDescStatus.Default.(uint8)
	// cloudfiletagDescTenantID is the schema descriptor for tenant_id field.
	cloudfiletagDescTenantID := cloudfiletagMixinFields2[0].Descriptor()
	// cloudfiletag.DefaultTenantID holds the default value on creation for the tenant_id field.
	cloudfiletag.DefaultTenantID = cloudfiletagDescTenantID.Default.(uint64)
	fileMixin := schema.File{}.Mixin()
	file.Policy = privacy.NewPolicies(schema.File{})
	file.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := file.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	fileHooks := schema.File{}.Hooks()

	file.Hooks[1] = fileHooks[0]
	fileMixinFields0 := fileMixin[0].Fields()
	_ = fileMixinFields0
	fileMixinFields1 := fileMixin[1].Fields()
	_ = fileMixinFields1
	fileMixinFields2 := fileMixin[2].Fields()
	_ = fileMixinFields2
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileMixinFields0[1].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
	// fileDescUpdatedAt is the schema descriptor for updated_at field.
	fileDescUpdatedAt := fileMixinFields0[2].Descriptor()
	// file.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	file.DefaultUpdatedAt = fileDescUpdatedAt.Default.(func() time.Time)
	// file.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	file.UpdateDefaultUpdatedAt = fileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// fileDescStatus is the schema descriptor for status field.
	fileDescStatus := fileMixinFields1[0].Descriptor()
	// file.DefaultStatus holds the default value on creation for the status field.
	file.DefaultStatus = fileDescStatus.Default.(uint8)
	// fileDescTenantID is the schema descriptor for tenant_id field.
	fileDescTenantID := fileMixinFields2[0].Descriptor()
	// file.DefaultTenantID holds the default value on creation for the tenant_id field.
	file.DefaultTenantID = fileDescTenantID.Default.(uint64)
	filetagMixin := schema.FileTag{}.Mixin()
	filetag.Policy = privacy.NewPolicies(schema.FileTag{})
	filetag.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := filetag.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	filetagHooks := schema.FileTag{}.Hooks()

	filetag.Hooks[1] = filetagHooks[0]
	filetagMixinFields0 := filetagMixin[0].Fields()
	_ = filetagMixinFields0
	filetagMixinFields1 := filetagMixin[1].Fields()
	_ = filetagMixinFields1
	filetagMixinFields2 := filetagMixin[2].Fields()
	_ = filetagMixinFields2
	filetagFields := schema.FileTag{}.Fields()
	_ = filetagFields
	// filetagDescCreatedAt is the schema descriptor for created_at field.
	filetagDescCreatedAt := filetagMixinFields0[1].Descriptor()
	// filetag.DefaultCreatedAt holds the default value on creation for the created_at field.
	filetag.DefaultCreatedAt = filetagDescCreatedAt.Default.(func() time.Time)
	// filetagDescUpdatedAt is the schema descriptor for updated_at field.
	filetagDescUpdatedAt := filetagMixinFields0[2].Descriptor()
	// filetag.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	filetag.DefaultUpdatedAt = filetagDescUpdatedAt.Default.(func() time.Time)
	// filetag.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	filetag.UpdateDefaultUpdatedAt = filetagDescUpdatedAt.UpdateDefault.(func() time.Time)
	// filetagDescStatus is the schema descriptor for status field.
	filetagDescStatus := filetagMixinFields1[0].Descriptor()
	// filetag.DefaultStatus holds the default value on creation for the status field.
	filetag.DefaultStatus = filetagDescStatus.Default.(uint8)
	// filetagDescTenantID is the schema descriptor for tenant_id field.
	filetagDescTenantID := filetagMixinFields2[0].Descriptor()
	// filetag.DefaultTenantID holds the default value on creation for the tenant_id field.
	filetag.DefaultTenantID = filetagDescTenantID.Default.(uint64)
	storageproviderMixin := schema.StorageProvider{}.Mixin()
	storageprovider.Policy = privacy.NewPolicies(schema.StorageProvider{})
	storageprovider.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := storageprovider.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	storageproviderHooks := schema.StorageProvider{}.Hooks()

	storageprovider.Hooks[1] = storageproviderHooks[0]
	storageproviderMixinFields0 := storageproviderMixin[0].Fields()
	_ = storageproviderMixinFields0
	storageproviderMixinFields1 := storageproviderMixin[1].Fields()
	_ = storageproviderMixinFields1
	storageproviderMixinFields2 := storageproviderMixin[2].Fields()
	_ = storageproviderMixinFields2
	storageproviderFields := schema.StorageProvider{}.Fields()
	_ = storageproviderFields
	// storageproviderDescCreatedAt is the schema descriptor for created_at field.
	storageproviderDescCreatedAt := storageproviderMixinFields0[1].Descriptor()
	// storageprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	storageprovider.DefaultCreatedAt = storageproviderDescCreatedAt.Default.(func() time.Time)
	// storageproviderDescUpdatedAt is the schema descriptor for updated_at field.
	storageproviderDescUpdatedAt := storageproviderMixinFields0[2].Descriptor()
	// storageprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	storageprovider.DefaultUpdatedAt = storageproviderDescUpdatedAt.Default.(func() time.Time)
	// storageprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	storageprovider.UpdateDefaultUpdatedAt = storageproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// storageproviderDescState is the schema descriptor for state field.
	storageproviderDescState := storageproviderMixinFields1[0].Descriptor()
	// storageprovider.DefaultState holds the default value on creation for the state field.
	storageprovider.DefaultState = storageproviderDescState.Default.(bool)
	// storageproviderDescTenantID is the schema descriptor for tenant_id field.
	storageproviderDescTenantID := storageproviderMixinFields2[0].Descriptor()
	// storageprovider.DefaultTenantID holds the default value on creation for the tenant_id field.
	storageprovider.DefaultTenantID = storageproviderDescTenantID.Default.(uint64)
	// storageproviderDescIsDefault is the schema descriptor for is_default field.
	storageproviderDescIsDefault := storageproviderFields[7].Descriptor()
	// storageprovider.DefaultIsDefault holds the default value on creation for the is_default field.
	storageprovider.DefaultIsDefault = storageproviderDescIsDefault.Default.(bool)
	// storageproviderDescUseCdn is the schema descriptor for use_cdn field.
	storageproviderDescUseCdn := storageproviderFields[8].Descriptor()
	// storageprovider.DefaultUseCdn holds the default value on creation for the use_cdn field.
	storageprovider.DefaultUseCdn = storageproviderDescUseCdn.Default.(bool)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
