// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"mingyang.com/admin-simple-admin-file/ent/apk"
)

// APK版本记录
type Apk struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Status 1: normal 2: ban | 状态 1 正常 2 禁用
	Status uint8 `json:"status,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// APK名称
	Name string `json:"name,omitempty"`
	// 版本号
	Version string `json:"version,omitempty"`
	// 版本代码(内部版本号)
	VersionCode string `json:"version_code,omitempty"`
	// 文件id
	FileID uint64 `json:"file_id,omitempty"`
	// 文件大小
	FileSize uint64 `json:"file_size,omitempty"`
	// 文件id ｜ 下载地址
	FileURL string `json:"file_url,omitempty"`
	// 文件MD5值
	Md5 string `json:"md5,omitempty"`
	// 文件SHA1值
	Sha1 string `json:"sha1,omitempty"`
	// 文件SHA256值
	Sha256 string `json:"sha256,omitempty"`
	// 应用包名
	PackageName string `json:"package_name,omitempty"`
	// 版本描述
	Description string `json:"description,omitempty"`
	// 更新日志
	UpdateLog string `json:"update_log,omitempty"`
	// 是否强制更新
	IsForceUpdate bool `json:"is_force_update,omitempty"`
	// 下载次数
	DownloadCount int64 `json:"download_count,omitempty"`
	// android ｜ ios
	Category     string `json:"category,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Apk) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apk.FieldIsForceUpdate:
			values[i] = new(sql.NullBool)
		case apk.FieldID, apk.FieldStatus, apk.FieldTenantID, apk.FieldFileID, apk.FieldFileSize, apk.FieldDownloadCount:
			values[i] = new(sql.NullInt64)
		case apk.FieldName, apk.FieldVersion, apk.FieldVersionCode, apk.FieldFileURL, apk.FieldMd5, apk.FieldSha1, apk.FieldSha256, apk.FieldPackageName, apk.FieldDescription, apk.FieldUpdateLog, apk.FieldCategory:
			values[i] = new(sql.NullString)
		case apk.FieldCreatedAt, apk.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Apk fields.
func (_m *Apk) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apk.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case apk.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apk.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case apk.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uint8(value.Int64)
			}
		case apk.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint64(value.Int64)
			}
		case apk.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case apk.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case apk.FieldVersionCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version_code", values[i])
			} else if value.Valid {
				_m.VersionCode = value.String
			}
		case apk.FieldFileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_id", values[i])
			} else if value.Valid {
				_m.FileID = uint64(value.Int64)
			}
		case apk.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = uint64(value.Int64)
			}
		case apk.FieldFileURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_url", values[i])
			} else if value.Valid {
				_m.FileURL = value.String
			}
		case apk.FieldMd5:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field md5", values[i])
			} else if value.Valid {
				_m.Md5 = value.String
			}
		case apk.FieldSha1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha1", values[i])
			} else if value.Valid {
				_m.Sha1 = value.String
			}
		case apk.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case apk.FieldPackageName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field package_name", values[i])
			} else if value.Valid {
				_m.PackageName = value.String
			}
		case apk.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case apk.FieldUpdateLog:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field update_log", values[i])
			} else if value.Valid {
				_m.UpdateLog = value.String
			}
		case apk.FieldIsForceUpdate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_force_update", values[i])
			} else if value.Valid {
				_m.IsForceUpdate = value.Bool
			}
		case apk.FieldDownloadCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field download_count", values[i])
			} else if value.Valid {
				_m.DownloadCount = value.Int64
			}
		case apk.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Apk.
// This includes values selected through modifiers, order, etc.
func (_m *Apk) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Apk.
// Note that you need to call Apk.Unwrap() before calling this method if this Apk
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Apk) Update() *ApkUpdateOne {
	return NewApkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Apk entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Apk) Unwrap() *Apk {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Apk is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Apk) String() string {
	var builder strings.Builder
	builder.WriteString("Apk(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("version_code=")
	builder.WriteString(_m.VersionCode)
	builder.WriteString(", ")
	builder.WriteString("file_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileID))
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	builder.WriteString("file_url=")
	builder.WriteString(_m.FileURL)
	builder.WriteString(", ")
	builder.WriteString("md5=")
	builder.WriteString(_m.Md5)
	builder.WriteString(", ")
	builder.WriteString("sha1=")
	builder.WriteString(_m.Sha1)
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("package_name=")
	builder.WriteString(_m.PackageName)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("update_log=")
	builder.WriteString(_m.UpdateLog)
	builder.WriteString(", ")
	builder.WriteString("is_force_update=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsForceUpdate))
	builder.WriteString(", ")
	builder.WriteString("download_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DownloadCount))
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteByte(')')
	return builder.String()
}

// Apks is a parsable slice of Apk.
type Apks []*Apk
