// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mingyang.com/admin-simple-admin-file/ent/apk"
	"mingyang.com/admin-simple-admin-file/ent/predicate"
)

// ApkUpdate is the builder for updating Apk entities.
type ApkUpdate struct {
	config
	hooks    []Hook
	mutation *ApkMutation
}

// Where appends a list predicates to the ApkUpdate builder.
func (_u *ApkUpdate) Where(ps ...predicate.Apk) *ApkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApkUpdate) SetUpdatedAt(v time.Time) *ApkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApkUpdate) SetStatus(v uint8) *ApkUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableStatus(v *uint8) *ApkUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ApkUpdate) AddStatus(v int8) *ApkUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ApkUpdate) ClearStatus() *ApkUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetName sets the "name" field.
func (_u *ApkUpdate) SetName(v string) *ApkUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableName(v *string) *ApkUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ApkUpdate) SetVersion(v string) *ApkUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableVersion(v *string) *ApkUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetVersionCode sets the "version_code" field.
func (_u *ApkUpdate) SetVersionCode(v string) *ApkUpdate {
	_u.mutation.SetVersionCode(v)
	return _u
}

// SetNillableVersionCode sets the "version_code" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableVersionCode(v *string) *ApkUpdate {
	if v != nil {
		_u.SetVersionCode(*v)
	}
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *ApkUpdate) SetFileID(v uint64) *ApkUpdate {
	_u.mutation.ResetFileID()
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableFileID(v *uint64) *ApkUpdate {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// AddFileID adds value to the "file_id" field.
func (_u *ApkUpdate) AddFileID(v int64) *ApkUpdate {
	_u.mutation.AddFileID(v)
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ApkUpdate) SetFileSize(v uint64) *ApkUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableFileSize(v *uint64) *ApkUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *ApkUpdate) AddFileSize(v int64) *ApkUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// ClearFileSize clears the value of the "file_size" field.
func (_u *ApkUpdate) ClearFileSize() *ApkUpdate {
	_u.mutation.ClearFileSize()
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *ApkUpdate) SetFileURL(v string) *ApkUpdate {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableFileURL(v *string) *ApkUpdate {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// SetMd5 sets the "md5" field.
func (_u *ApkUpdate) SetMd5(v string) *ApkUpdate {
	_u.mutation.SetMd5(v)
	return _u
}

// SetNillableMd5 sets the "md5" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableMd5(v *string) *ApkUpdate {
	if v != nil {
		_u.SetMd5(*v)
	}
	return _u
}

// ClearMd5 clears the value of the "md5" field.
func (_u *ApkUpdate) ClearMd5() *ApkUpdate {
	_u.mutation.ClearMd5()
	return _u
}

// SetSha1 sets the "sha1" field.
func (_u *ApkUpdate) SetSha1(v string) *ApkUpdate {
	_u.mutation.SetSha1(v)
	return _u
}

// SetNillableSha1 sets the "sha1" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableSha1(v *string) *ApkUpdate {
	if v != nil {
		_u.SetSha1(*v)
	}
	return _u
}

// ClearSha1 clears the value of the "sha1" field.
func (_u *ApkUpdate) ClearSha1() *ApkUpdate {
	_u.mutation.ClearSha1()
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ApkUpdate) SetSha256(v string) *ApkUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableSha256(v *string) *ApkUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// ClearSha256 clears the value of the "sha256" field.
func (_u *ApkUpdate) ClearSha256() *ApkUpdate {
	_u.mutation.ClearSha256()
	return _u
}

// SetPackageName sets the "package_name" field.
func (_u *ApkUpdate) SetPackageName(v string) *ApkUpdate {
	_u.mutation.SetPackageName(v)
	return _u
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (_u *ApkUpdate) SetNillablePackageName(v *string) *ApkUpdate {
	if v != nil {
		_u.SetPackageName(*v)
	}
	return _u
}

// ClearPackageName clears the value of the "package_name" field.
func (_u *ApkUpdate) ClearPackageName() *ApkUpdate {
	_u.mutation.ClearPackageName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ApkUpdate) SetDescription(v string) *ApkUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableDescription(v *string) *ApkUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ApkUpdate) ClearDescription() *ApkUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdateLog sets the "update_log" field.
func (_u *ApkUpdate) SetUpdateLog(v string) *ApkUpdate {
	_u.mutation.SetUpdateLog(v)
	return _u
}

// SetNillableUpdateLog sets the "update_log" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableUpdateLog(v *string) *ApkUpdate {
	if v != nil {
		_u.SetUpdateLog(*v)
	}
	return _u
}

// ClearUpdateLog clears the value of the "update_log" field.
func (_u *ApkUpdate) ClearUpdateLog() *ApkUpdate {
	_u.mutation.ClearUpdateLog()
	return _u
}

// SetIsForceUpdate sets the "is_force_update" field.
func (_u *ApkUpdate) SetIsForceUpdate(v bool) *ApkUpdate {
	_u.mutation.SetIsForceUpdate(v)
	return _u
}

// SetNillableIsForceUpdate sets the "is_force_update" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableIsForceUpdate(v *bool) *ApkUpdate {
	if v != nil {
		_u.SetIsForceUpdate(*v)
	}
	return _u
}

// SetDownloadCount sets the "download_count" field.
func (_u *ApkUpdate) SetDownloadCount(v int64) *ApkUpdate {
	_u.mutation.ResetDownloadCount()
	_u.mutation.SetDownloadCount(v)
	return _u
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableDownloadCount(v *int64) *ApkUpdate {
	if v != nil {
		_u.SetDownloadCount(*v)
	}
	return _u
}

// AddDownloadCount adds value to the "download_count" field.
func (_u *ApkUpdate) AddDownloadCount(v int64) *ApkUpdate {
	_u.mutation.AddDownloadCount(v)
	return _u
}

// SetCategory sets the "category" field.
func (_u *ApkUpdate) SetCategory(v string) *ApkUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ApkUpdate) SetNillableCategory(v *string) *ApkUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// Mutation returns the ApkMutation object of the builder.
func (_u *ApkUpdate) Mutation() *ApkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApkUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apk.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ApkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(apk.Table, apk.Columns, sqlgraph.NewFieldSpec(apk.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apk.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(apk.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(apk.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(apk.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apk.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(apk.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.VersionCode(); ok {
		_spec.SetField(apk.FieldVersionCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(apk.FieldFileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFileID(); ok {
		_spec.AddField(apk.FieldFileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(apk.FieldFileSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(apk.FieldFileSize, field.TypeUint64, value)
	}
	if _u.mutation.FileSizeCleared() {
		_spec.ClearField(apk.FieldFileSize, field.TypeUint64)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(apk.FieldFileURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Md5(); ok {
		_spec.SetField(apk.FieldMd5, field.TypeString, value)
	}
	if _u.mutation.Md5Cleared() {
		_spec.ClearField(apk.FieldMd5, field.TypeString)
	}
	if value, ok := _u.mutation.Sha1(); ok {
		_spec.SetField(apk.FieldSha1, field.TypeString, value)
	}
	if _u.mutation.Sha1Cleared() {
		_spec.ClearField(apk.FieldSha1, field.TypeString)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(apk.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.Sha256Cleared() {
		_spec.ClearField(apk.FieldSha256, field.TypeString)
	}
	if value, ok := _u.mutation.PackageName(); ok {
		_spec.SetField(apk.FieldPackageName, field.TypeString, value)
	}
	if _u.mutation.PackageNameCleared() {
		_spec.ClearField(apk.FieldPackageName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apk.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(apk.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateLog(); ok {
		_spec.SetField(apk.FieldUpdateLog, field.TypeString, value)
	}
	if _u.mutation.UpdateLogCleared() {
		_spec.ClearField(apk.FieldUpdateLog, field.TypeString)
	}
	if value, ok := _u.mutation.IsForceUpdate(); ok {
		_spec.SetField(apk.FieldIsForceUpdate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DownloadCount(); ok {
		_spec.SetField(apk.FieldDownloadCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownloadCount(); ok {
		_spec.AddField(apk.FieldDownloadCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(apk.FieldCategory, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApkUpdateOne is the builder for updating a single Apk entity.
type ApkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApkMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApkUpdateOne) SetUpdatedAt(v time.Time) *ApkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApkUpdateOne) SetStatus(v uint8) *ApkUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableStatus(v *uint8) *ApkUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ApkUpdateOne) AddStatus(v int8) *ApkUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ApkUpdateOne) ClearStatus() *ApkUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetName sets the "name" field.
func (_u *ApkUpdateOne) SetName(v string) *ApkUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableName(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ApkUpdateOne) SetVersion(v string) *ApkUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableVersion(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetVersionCode sets the "version_code" field.
func (_u *ApkUpdateOne) SetVersionCode(v string) *ApkUpdateOne {
	_u.mutation.SetVersionCode(v)
	return _u
}

// SetNillableVersionCode sets the "version_code" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableVersionCode(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetVersionCode(*v)
	}
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *ApkUpdateOne) SetFileID(v uint64) *ApkUpdateOne {
	_u.mutation.ResetFileID()
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableFileID(v *uint64) *ApkUpdateOne {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// AddFileID adds value to the "file_id" field.
func (_u *ApkUpdateOne) AddFileID(v int64) *ApkUpdateOne {
	_u.mutation.AddFileID(v)
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ApkUpdateOne) SetFileSize(v uint64) *ApkUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableFileSize(v *uint64) *ApkUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *ApkUpdateOne) AddFileSize(v int64) *ApkUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// ClearFileSize clears the value of the "file_size" field.
func (_u *ApkUpdateOne) ClearFileSize() *ApkUpdateOne {
	_u.mutation.ClearFileSize()
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *ApkUpdateOne) SetFileURL(v string) *ApkUpdateOne {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableFileURL(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// SetMd5 sets the "md5" field.
func (_u *ApkUpdateOne) SetMd5(v string) *ApkUpdateOne {
	_u.mutation.SetMd5(v)
	return _u
}

// SetNillableMd5 sets the "md5" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableMd5(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetMd5(*v)
	}
	return _u
}

// ClearMd5 clears the value of the "md5" field.
func (_u *ApkUpdateOne) ClearMd5() *ApkUpdateOne {
	_u.mutation.ClearMd5()
	return _u
}

// SetSha1 sets the "sha1" field.
func (_u *ApkUpdateOne) SetSha1(v string) *ApkUpdateOne {
	_u.mutation.SetSha1(v)
	return _u
}

// SetNillableSha1 sets the "sha1" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableSha1(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetSha1(*v)
	}
	return _u
}

// ClearSha1 clears the value of the "sha1" field.
func (_u *ApkUpdateOne) ClearSha1() *ApkUpdateOne {
	_u.mutation.ClearSha1()
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ApkUpdateOne) SetSha256(v string) *ApkUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableSha256(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// ClearSha256 clears the value of the "sha256" field.
func (_u *ApkUpdateOne) ClearSha256() *ApkUpdateOne {
	_u.mutation.ClearSha256()
	return _u
}

// SetPackageName sets the "package_name" field.
func (_u *ApkUpdateOne) SetPackageName(v string) *ApkUpdateOne {
	_u.mutation.SetPackageName(v)
	return _u
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillablePackageName(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetPackageName(*v)
	}
	return _u
}

// ClearPackageName clears the value of the "package_name" field.
func (_u *ApkUpdateOne) ClearPackageName() *ApkUpdateOne {
	_u.mutation.ClearPackageName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ApkUpdateOne) SetDescription(v string) *ApkUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableDescription(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ApkUpdateOne) ClearDescription() *ApkUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdateLog sets the "update_log" field.
func (_u *ApkUpdateOne) SetUpdateLog(v string) *ApkUpdateOne {
	_u.mutation.SetUpdateLog(v)
	return _u
}

// SetNillableUpdateLog sets the "update_log" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableUpdateLog(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetUpdateLog(*v)
	}
	return _u
}

// ClearUpdateLog clears the value of the "update_log" field.
func (_u *ApkUpdateOne) ClearUpdateLog() *ApkUpdateOne {
	_u.mutation.ClearUpdateLog()
	return _u
}

// SetIsForceUpdate sets the "is_force_update" field.
func (_u *ApkUpdateOne) SetIsForceUpdate(v bool) *ApkUpdateOne {
	_u.mutation.SetIsForceUpdate(v)
	return _u
}

// SetNillableIsForceUpdate sets the "is_force_update" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableIsForceUpdate(v *bool) *ApkUpdateOne {
	if v != nil {
		_u.SetIsForceUpdate(*v)
	}
	return _u
}

// SetDownloadCount sets the "download_count" field.
func (_u *ApkUpdateOne) SetDownloadCount(v int64) *ApkUpdateOne {
	_u.mutation.ResetDownloadCount()
	_u.mutation.SetDownloadCount(v)
	return _u
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableDownloadCount(v *int64) *ApkUpdateOne {
	if v != nil {
		_u.SetDownloadCount(*v)
	}
	return _u
}

// AddDownloadCount adds value to the "download_count" field.
func (_u *ApkUpdateOne) AddDownloadCount(v int64) *ApkUpdateOne {
	_u.mutation.AddDownloadCount(v)
	return _u
}

// SetCategory sets the "category" field.
func (_u *ApkUpdateOne) SetCategory(v string) *ApkUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ApkUpdateOne) SetNillableCategory(v *string) *ApkUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// Mutation returns the ApkMutation object of the builder.
func (_u *ApkUpdateOne) Mutation() *ApkMutation {
	return _u.mutation
}

// Where appends a list predicates to the ApkUpdate builder.
func (_u *ApkUpdateOne) Where(ps ...predicate.Apk) *ApkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApkUpdateOne) Select(field string, fields ...string) *ApkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Apk entity.
func (_u *ApkUpdateOne) Save(ctx context.Context) (*Apk, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApkUpdateOne) SaveX(ctx context.Context) *Apk {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApkUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apk.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ApkUpdateOne) sqlSave(ctx context.Context) (_node *Apk, err error) {
	_spec := sqlgraph.NewUpdateSpec(apk.Table, apk.Columns, sqlgraph.NewFieldSpec(apk.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Apk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apk.FieldID)
		for _, f := range fields {
			if !apk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apk.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(apk.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(apk.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(apk.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apk.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(apk.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.VersionCode(); ok {
		_spec.SetField(apk.FieldVersionCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(apk.FieldFileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFileID(); ok {
		_spec.AddField(apk.FieldFileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(apk.FieldFileSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(apk.FieldFileSize, field.TypeUint64, value)
	}
	if _u.mutation.FileSizeCleared() {
		_spec.ClearField(apk.FieldFileSize, field.TypeUint64)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(apk.FieldFileURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Md5(); ok {
		_spec.SetField(apk.FieldMd5, field.TypeString, value)
	}
	if _u.mutation.Md5Cleared() {
		_spec.ClearField(apk.FieldMd5, field.TypeString)
	}
	if value, ok := _u.mutation.Sha1(); ok {
		_spec.SetField(apk.FieldSha1, field.TypeString, value)
	}
	if _u.mutation.Sha1Cleared() {
		_spec.ClearField(apk.FieldSha1, field.TypeString)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(apk.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.Sha256Cleared() {
		_spec.ClearField(apk.FieldSha256, field.TypeString)
	}
	if value, ok := _u.mutation.PackageName(); ok {
		_spec.SetField(apk.FieldPackageName, field.TypeString, value)
	}
	if _u.mutation.PackageNameCleared() {
		_spec.ClearField(apk.FieldPackageName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apk.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(apk.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateLog(); ok {
		_spec.SetField(apk.FieldUpdateLog, field.TypeString, value)
	}
	if _u.mutation.UpdateLogCleared() {
		_spec.ClearField(apk.FieldUpdateLog, field.TypeString)
	}
	if value, ok := _u.mutation.IsForceUpdate(); ok {
		_spec.SetField(apk.FieldIsForceUpdate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DownloadCount(); ok {
		_spec.SetField(apk.FieldDownloadCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownloadCount(); ok {
		_spec.AddField(apk.FieldDownloadCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(apk.FieldCategory, field.TypeString, value)
	}
	_node = &Apk{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
