// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mingyang-admin-simple-admin-file/ent/apk"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApkCreate is the builder for creating a Apk entity.
type ApkCreate struct {
	config
	mutation *ApkMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ApkCreate) SetCreatedAt(v time.Time) *ApkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ApkCreate) SetNillableCreatedAt(v *time.Time) *ApkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ApkCreate) SetUpdatedAt(v time.Time) *ApkCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ApkCreate) SetNillableUpdatedAt(v *time.Time) *ApkCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ApkCreate) SetStatus(v uint8) *ApkCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ApkCreate) SetNillableStatus(v *uint8) *ApkCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ApkCreate) SetTenantID(v uint64) *ApkCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ApkCreate) SetNillableTenantID(v *uint64) *ApkCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ApkCreate) SetName(v string) *ApkCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ApkCreate) SetVersion(v string) *ApkCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetVersionCode sets the "version_code" field.
func (_c *ApkCreate) SetVersionCode(v string) *ApkCreate {
	_c.mutation.SetVersionCode(v)
	return _c
}

// SetFileID sets the "file_id" field.
func (_c *ApkCreate) SetFileID(v uint64) *ApkCreate {
	_c.mutation.SetFileID(v)
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *ApkCreate) SetFileSize(v uint64) *ApkCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_c *ApkCreate) SetNillableFileSize(v *uint64) *ApkCreate {
	if v != nil {
		_c.SetFileSize(*v)
	}
	return _c
}

// SetFileURL sets the "file_url" field.
func (_c *ApkCreate) SetFileURL(v string) *ApkCreate {
	_c.mutation.SetFileURL(v)
	return _c
}

// SetMd5 sets the "md5" field.
func (_c *ApkCreate) SetMd5(v string) *ApkCreate {
	_c.mutation.SetMd5(v)
	return _c
}

// SetNillableMd5 sets the "md5" field if the given value is not nil.
func (_c *ApkCreate) SetNillableMd5(v *string) *ApkCreate {
	if v != nil {
		_c.SetMd5(*v)
	}
	return _c
}

// SetSha1 sets the "sha1" field.
func (_c *ApkCreate) SetSha1(v string) *ApkCreate {
	_c.mutation.SetSha1(v)
	return _c
}

// SetNillableSha1 sets the "sha1" field if the given value is not nil.
func (_c *ApkCreate) SetNillableSha1(v *string) *ApkCreate {
	if v != nil {
		_c.SetSha1(*v)
	}
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *ApkCreate) SetSha256(v string) *ApkCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_c *ApkCreate) SetNillableSha256(v *string) *ApkCreate {
	if v != nil {
		_c.SetSha256(*v)
	}
	return _c
}

// SetPackageName sets the "package_name" field.
func (_c *ApkCreate) SetPackageName(v string) *ApkCreate {
	_c.mutation.SetPackageName(v)
	return _c
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (_c *ApkCreate) SetNillablePackageName(v *string) *ApkCreate {
	if v != nil {
		_c.SetPackageName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ApkCreate) SetDescription(v string) *ApkCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ApkCreate) SetNillableDescription(v *string) *ApkCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetUpdateLog sets the "update_log" field.
func (_c *ApkCreate) SetUpdateLog(v string) *ApkCreate {
	_c.mutation.SetUpdateLog(v)
	return _c
}

// SetNillableUpdateLog sets the "update_log" field if the given value is not nil.
func (_c *ApkCreate) SetNillableUpdateLog(v *string) *ApkCreate {
	if v != nil {
		_c.SetUpdateLog(*v)
	}
	return _c
}

// SetIsForceUpdate sets the "is_force_update" field.
func (_c *ApkCreate) SetIsForceUpdate(v bool) *ApkCreate {
	_c.mutation.SetIsForceUpdate(v)
	return _c
}

// SetNillableIsForceUpdate sets the "is_force_update" field if the given value is not nil.
func (_c *ApkCreate) SetNillableIsForceUpdate(v *bool) *ApkCreate {
	if v != nil {
		_c.SetIsForceUpdate(*v)
	}
	return _c
}

// SetDownloadCount sets the "download_count" field.
func (_c *ApkCreate) SetDownloadCount(v int64) *ApkCreate {
	_c.mutation.SetDownloadCount(v)
	return _c
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_c *ApkCreate) SetNillableDownloadCount(v *int64) *ApkCreate {
	if v != nil {
		_c.SetDownloadCount(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *ApkCreate) SetCategory(v string) *ApkCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ApkCreate) SetID(v uint64) *ApkCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ApkMutation object of the builder.
func (_c *ApkCreate) Mutation() *ApkMutation {
	return _c.mutation
}

// Save creates the Apk in the database.
func (_c *ApkCreate) Save(ctx context.Context) (*Apk, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApkCreate) SaveX(ctx context.Context) *Apk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApkCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apk.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apk.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := apk.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := apk.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		v := apk.DefaultFileSize
		_c.mutation.SetFileSize(v)
	}
	if _, ok := _c.mutation.IsForceUpdate(); !ok {
		v := apk.DefaultIsForceUpdate
		_c.mutation.SetIsForceUpdate(v)
	}
	if _, ok := _c.mutation.DownloadCount(); !ok {
		v := apk.DefaultDownloadCount
		_c.mutation.SetDownloadCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApkCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Apk.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Apk.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Apk.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Apk.name"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Apk.version"`)}
	}
	if _, ok := _c.mutation.VersionCode(); !ok {
		return &ValidationError{Name: "version_code", err: errors.New(`ent: missing required field "Apk.version_code"`)}
	}
	if _, ok := _c.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`ent: missing required field "Apk.file_id"`)}
	}
	if _, ok := _c.mutation.FileURL(); !ok {
		return &ValidationError{Name: "file_url", err: errors.New(`ent: missing required field "Apk.file_url"`)}
	}
	if _, ok := _c.mutation.IsForceUpdate(); !ok {
		return &ValidationError{Name: "is_force_update", err: errors.New(`ent: missing required field "Apk.is_force_update"`)}
	}
	if _, ok := _c.mutation.DownloadCount(); !ok {
		return &ValidationError{Name: "download_count", err: errors.New(`ent: missing required field "Apk.download_count"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Apk.category"`)}
	}
	return nil
}

func (_c *ApkCreate) sqlSave(ctx context.Context) (*Apk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ApkCreate) createSpec() (*Apk, *sqlgraph.CreateSpec) {
	var (
		_node = &Apk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apk.Table, sqlgraph.NewFieldSpec(apk.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apk.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apk.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(apk.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(apk.FieldTenantID, field.TypeUint64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(apk.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(apk.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.VersionCode(); ok {
		_spec.SetField(apk.FieldVersionCode, field.TypeString, value)
		_node.VersionCode = value
	}
	if value, ok := _c.mutation.FileID(); ok {
		_spec.SetField(apk.FieldFileID, field.TypeUint64, value)
		_node.FileID = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(apk.FieldFileSize, field.TypeUint64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.FileURL(); ok {
		_spec.SetField(apk.FieldFileURL, field.TypeString, value)
		_node.FileURL = value
	}
	if value, ok := _c.mutation.Md5(); ok {
		_spec.SetField(apk.FieldMd5, field.TypeString, value)
		_node.Md5 = value
	}
	if value, ok := _c.mutation.Sha1(); ok {
		_spec.SetField(apk.FieldSha1, field.TypeString, value)
		_node.Sha1 = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(apk.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.PackageName(); ok {
		_spec.SetField(apk.FieldPackageName, field.TypeString, value)
		_node.PackageName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(apk.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.UpdateLog(); ok {
		_spec.SetField(apk.FieldUpdateLog, field.TypeString, value)
		_node.UpdateLog = value
	}
	if value, ok := _c.mutation.IsForceUpdate(); ok {
		_spec.SetField(apk.FieldIsForceUpdate, field.TypeBool, value)
		_node.IsForceUpdate = value
	}
	if value, ok := _c.mutation.DownloadCount(); ok {
		_spec.SetField(apk.FieldDownloadCount, field.TypeInt64, value)
		_node.DownloadCount = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(apk.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	return _node, _spec
}

// ApkCreateBulk is the builder for creating many Apk entities in bulk.
type ApkCreateBulk struct {
	config
	err      error
	builders []*ApkCreate
}

// Save creates the Apk entities in the database.
func (_c *ApkCreateBulk) Save(ctx context.Context) ([]*Apk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Apk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApkCreateBulk) SaveX(ctx context.Context) []*Apk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
