// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mingyang-admin-simple-admin-file/ent/apk"
	"mingyang-admin-simple-admin-file/ent/cloudfile"
	"mingyang-admin-simple-admin-file/ent/cloudfiletag"
	"mingyang-admin-simple-admin-file/ent/file"
	"mingyang-admin-simple-admin-file/ent/filetag"
	"mingyang-admin-simple-admin-file/ent/predicate"
	"mingyang-admin-simple-admin-file/ent/storageprovider"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 6)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   apk.Table,
			Columns: apk.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: apk.FieldID,
			},
		},
		Type: "Apk",
		Fields: map[string]*sqlgraph.FieldSpec{
			apk.FieldCreatedAt:     {Type: field.TypeTime, Column: apk.FieldCreatedAt},
			apk.FieldUpdatedAt:     {Type: field.TypeTime, Column: apk.FieldUpdatedAt},
			apk.FieldStatus:        {Type: field.TypeUint8, Column: apk.FieldStatus},
			apk.FieldTenantID:      {Type: field.TypeUint64, Column: apk.FieldTenantID},
			apk.FieldName:          {Type: field.TypeString, Column: apk.FieldName},
			apk.FieldVersion:       {Type: field.TypeString, Column: apk.FieldVersion},
			apk.FieldVersionCode:   {Type: field.TypeString, Column: apk.FieldVersionCode},
			apk.FieldFileSize:      {Type: field.TypeUint64, Column: apk.FieldFileSize},
			apk.FieldFileID:        {Type: field.TypeUint64, Column: apk.FieldFileID},
			apk.FieldFilePath:      {Type: field.TypeString, Column: apk.FieldFilePath},
			apk.FieldMd5:           {Type: field.TypeString, Column: apk.FieldMd5},
			apk.FieldSha1:          {Type: field.TypeString, Column: apk.FieldSha1},
			apk.FieldSha256:        {Type: field.TypeString, Column: apk.FieldSha256},
			apk.FieldPackageName:   {Type: field.TypeString, Column: apk.FieldPackageName},
			apk.FieldDescription:   {Type: field.TypeString, Column: apk.FieldDescription},
			apk.FieldUpdateLog:     {Type: field.TypeString, Column: apk.FieldUpdateLog},
			apk.FieldIsForceUpdate: {Type: field.TypeBool, Column: apk.FieldIsForceUpdate},
			apk.FieldDownloadCount: {Type: field.TypeInt64, Column: apk.FieldDownloadCount},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   cloudfile.Table,
			Columns: cloudfile.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: cloudfile.FieldID,
			},
		},
		Type: "CloudFile",
		Fields: map[string]*sqlgraph.FieldSpec{
			cloudfile.FieldCreatedAt: {Type: field.TypeTime, Column: cloudfile.FieldCreatedAt},
			cloudfile.FieldUpdatedAt: {Type: field.TypeTime, Column: cloudfile.FieldUpdatedAt},
			cloudfile.FieldState:     {Type: field.TypeBool, Column: cloudfile.FieldState},
			cloudfile.FieldTenantID:  {Type: field.TypeUint64, Column: cloudfile.FieldTenantID},
			cloudfile.FieldName:      {Type: field.TypeString, Column: cloudfile.FieldName},
			cloudfile.FieldURL:       {Type: field.TypeString, Column: cloudfile.FieldURL},
			cloudfile.FieldSize:      {Type: field.TypeUint64, Column: cloudfile.FieldSize},
			cloudfile.FieldFileType:  {Type: field.TypeUint8, Column: cloudfile.FieldFileType},
			cloudfile.FieldUserID:    {Type: field.TypeString, Column: cloudfile.FieldUserID},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   cloudfiletag.Table,
			Columns: cloudfiletag.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: cloudfiletag.FieldID,
			},
		},
		Type: "CloudFileTag",
		Fields: map[string]*sqlgraph.FieldSpec{
			cloudfiletag.FieldCreatedAt: {Type: field.TypeTime, Column: cloudfiletag.FieldCreatedAt},
			cloudfiletag.FieldUpdatedAt: {Type: field.TypeTime, Column: cloudfiletag.FieldUpdatedAt},
			cloudfiletag.FieldStatus:    {Type: field.TypeUint8, Column: cloudfiletag.FieldStatus},
			cloudfiletag.FieldTenantID:  {Type: field.TypeUint64, Column: cloudfiletag.FieldTenantID},
			cloudfiletag.FieldName:      {Type: field.TypeString, Column: cloudfiletag.FieldName},
			cloudfiletag.FieldRemark:    {Type: field.TypeString, Column: cloudfiletag.FieldRemark},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   file.Table,
			Columns: file.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: file.FieldID,
			},
		},
		Type: "File",
		Fields: map[string]*sqlgraph.FieldSpec{
			file.FieldCreatedAt: {Type: field.TypeTime, Column: file.FieldCreatedAt},
			file.FieldUpdatedAt: {Type: field.TypeTime, Column: file.FieldUpdatedAt},
			file.FieldStatus:    {Type: field.TypeUint8, Column: file.FieldStatus},
			file.FieldTenantID:  {Type: field.TypeUint64, Column: file.FieldTenantID},
			file.FieldName:      {Type: field.TypeString, Column: file.FieldName},
			file.FieldFileType:  {Type: field.TypeUint8, Column: file.FieldFileType},
			file.FieldSize:      {Type: field.TypeUint64, Column: file.FieldSize},
			file.FieldPath:      {Type: field.TypeString, Column: file.FieldPath},
			file.FieldUserID:    {Type: field.TypeString, Column: file.FieldUserID},
			file.FieldMd5:       {Type: field.TypeString, Column: file.FieldMd5},
		},
	}
	graph.Nodes[4] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   filetag.Table,
			Columns: filetag.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: filetag.FieldID,
			},
		},
		Type: "FileTag",
		Fields: map[string]*sqlgraph.FieldSpec{
			filetag.FieldCreatedAt: {Type: field.TypeTime, Column: filetag.FieldCreatedAt},
			filetag.FieldUpdatedAt: {Type: field.TypeTime, Column: filetag.FieldUpdatedAt},
			filetag.FieldStatus:    {Type: field.TypeUint8, Column: filetag.FieldStatus},
			filetag.FieldTenantID:  {Type: field.TypeUint64, Column: filetag.FieldTenantID},
			filetag.FieldName:      {Type: field.TypeString, Column: filetag.FieldName},
			filetag.FieldRemark:    {Type: field.TypeString, Column: filetag.FieldRemark},
		},
	}
	graph.Nodes[5] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   storageprovider.Table,
			Columns: storageprovider.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: storageprovider.FieldID,
			},
		},
		Type: "StorageProvider",
		Fields: map[string]*sqlgraph.FieldSpec{
			storageprovider.FieldCreatedAt: {Type: field.TypeTime, Column: storageprovider.FieldCreatedAt},
			storageprovider.FieldUpdatedAt: {Type: field.TypeTime, Column: storageprovider.FieldUpdatedAt},
			storageprovider.FieldState:     {Type: field.TypeBool, Column: storageprovider.FieldState},
			storageprovider.FieldTenantID:  {Type: field.TypeUint64, Column: storageprovider.FieldTenantID},
			storageprovider.FieldName:      {Type: field.TypeString, Column: storageprovider.FieldName},
			storageprovider.FieldBucket:    {Type: field.TypeString, Column: storageprovider.FieldBucket},
			storageprovider.FieldSecretID:  {Type: field.TypeString, Column: storageprovider.FieldSecretID},
			storageprovider.FieldSecretKey: {Type: field.TypeString, Column: storageprovider.FieldSecretKey},
			storageprovider.FieldEndpoint:  {Type: field.TypeString, Column: storageprovider.FieldEndpoint},
			storageprovider.FieldFolder:    {Type: field.TypeString, Column: storageprovider.FieldFolder},
			storageprovider.FieldRegion:    {Type: field.TypeString, Column: storageprovider.FieldRegion},
			storageprovider.FieldIsDefault: {Type: field.TypeBool, Column: storageprovider.FieldIsDefault},
			storageprovider.FieldUseCdn:    {Type: field.TypeBool, Column: storageprovider.FieldUseCdn},
			storageprovider.FieldCdnURL:    {Type: field.TypeString, Column: storageprovider.FieldCdnURL},
		},
	}
	graph.MustAddE(
		"storage_providers",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cloudfile.StorageProvidersTable,
			Columns: []string{cloudfile.StorageProvidersColumn},
			Bidi:    false,
		},
		"CloudFile",
		"StorageProvider",
	)
	graph.MustAddE(
		"tags",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cloudfile.TagsTable,
			Columns: cloudfile.TagsPrimaryKey,
			Bidi:    false,
		},
		"CloudFile",
		"CloudFileTag",
	)
	graph.MustAddE(
		"cloud_files",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   cloudfiletag.CloudFilesTable,
			Columns: cloudfiletag.CloudFilesPrimaryKey,
			Bidi:    false,
		},
		"CloudFileTag",
		"CloudFile",
	)
	graph.MustAddE(
		"tags",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   file.TagsTable,
			Columns: file.TagsPrimaryKey,
			Bidi:    false,
		},
		"File",
		"FileTag",
	)
	graph.MustAddE(
		"files",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   filetag.FilesTable,
			Columns: filetag.FilesPrimaryKey,
			Bidi:    false,
		},
		"FileTag",
		"File",
	)
	graph.MustAddE(
		"cloudfiles",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   storageprovider.CloudfilesTable,
			Columns: []string{storageprovider.CloudfilesColumn},
			Bidi:    false,
		},
		"StorageProvider",
		"CloudFile",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *ApkQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the ApkQuery builder.
func (_q *ApkQuery) Filter() *ApkFilter {
	return &ApkFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *ApkMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the ApkMutation builder.
func (m *ApkMutation) Filter() *ApkFilter {
	return &ApkFilter{config: m.config, predicateAdder: m}
}

// ApkFilter provides a generic filtering capability at runtime for ApkQuery.
type ApkFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *ApkFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint64 predicate on the id field.
func (f *ApkFilter) WhereID(p entql.Uint64P) {
	f.Where(p.Field(apk.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *ApkFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(apk.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *ApkFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(apk.FieldUpdatedAt))
}

// WhereStatus applies the entql uint8 predicate on the status field.
func (f *ApkFilter) WhereStatus(p entql.Uint8P) {
	f.Where(p.Field(apk.FieldStatus))
}

// WhereTenantID applies the entql uint64 predicate on the tenant_id field.
func (f *ApkFilter) WhereTenantID(p entql.Uint64P) {
	f.Where(p.Field(apk.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *ApkFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(apk.FieldName))
}

// WhereVersion applies the entql string predicate on the version field.
func (f *ApkFilter) WhereVersion(p entql.StringP) {
	f.Where(p.Field(apk.FieldVersion))
}

// WhereVersionCode applies the entql string predicate on the version_code field.
func (f *ApkFilter) WhereVersionCode(p entql.StringP) {
	f.Where(p.Field(apk.FieldVersionCode))
}

// WhereFileSize applies the entql uint64 predicate on the file_size field.
func (f *ApkFilter) WhereFileSize(p entql.Uint64P) {
	f.Where(p.Field(apk.FieldFileSize))
}

// WhereFileID applies the entql uint64 predicate on the file_id field.
func (f *ApkFilter) WhereFileID(p entql.Uint64P) {
	f.Where(p.Field(apk.FieldFileID))
}

// WhereFilePath applies the entql string predicate on the file_path field.
func (f *ApkFilter) WhereFilePath(p entql.StringP) {
	f.Where(p.Field(apk.FieldFilePath))
}

// WhereMd5 applies the entql string predicate on the md5 field.
func (f *ApkFilter) WhereMd5(p entql.StringP) {
	f.Where(p.Field(apk.FieldMd5))
}

// WhereSha1 applies the entql string predicate on the sha1 field.
func (f *ApkFilter) WhereSha1(p entql.StringP) {
	f.Where(p.Field(apk.FieldSha1))
}

// WhereSha256 applies the entql string predicate on the sha256 field.
func (f *ApkFilter) WhereSha256(p entql.StringP) {
	f.Where(p.Field(apk.FieldSha256))
}

// WherePackageName applies the entql string predicate on the package_name field.
func (f *ApkFilter) WherePackageName(p entql.StringP) {
	f.Where(p.Field(apk.FieldPackageName))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *ApkFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(apk.FieldDescription))
}

// WhereUpdateLog applies the entql string predicate on the update_log field.
func (f *ApkFilter) WhereUpdateLog(p entql.StringP) {
	f.Where(p.Field(apk.FieldUpdateLog))
}

// WhereIsForceUpdate applies the entql bool predicate on the is_force_update field.
func (f *ApkFilter) WhereIsForceUpdate(p entql.BoolP) {
	f.Where(p.Field(apk.FieldIsForceUpdate))
}

// WhereDownloadCount applies the entql int64 predicate on the download_count field.
func (f *ApkFilter) WhereDownloadCount(p entql.Int64P) {
	f.Where(p.Field(apk.FieldDownloadCount))
}

// addPredicate implements the predicateAdder interface.
func (_q *CloudFileQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the CloudFileQuery builder.
func (_q *CloudFileQuery) Filter() *CloudFileFilter {
	return &CloudFileFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *CloudFileMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the CloudFileMutation builder.
func (m *CloudFileMutation) Filter() *CloudFileFilter {
	return &CloudFileFilter{config: m.config, predicateAdder: m}
}

// CloudFileFilter provides a generic filtering capability at runtime for CloudFileQuery.
type CloudFileFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *CloudFileFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint64 predicate on the id field.
func (f *CloudFileFilter) WhereID(p entql.Uint64P) {
	f.Where(p.Field(cloudfile.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *CloudFileFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(cloudfile.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *CloudFileFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(cloudfile.FieldUpdatedAt))
}

// WhereState applies the entql bool predicate on the state field.
func (f *CloudFileFilter) WhereState(p entql.BoolP) {
	f.Where(p.Field(cloudfile.FieldState))
}

// WhereTenantID applies the entql uint64 predicate on the tenant_id field.
func (f *CloudFileFilter) WhereTenantID(p entql.Uint64P) {
	f.Where(p.Field(cloudfile.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *CloudFileFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(cloudfile.FieldName))
}

// WhereURL applies the entql string predicate on the url field.
func (f *CloudFileFilter) WhereURL(p entql.StringP) {
	f.Where(p.Field(cloudfile.FieldURL))
}

// WhereSize applies the entql uint64 predicate on the size field.
func (f *CloudFileFilter) WhereSize(p entql.Uint64P) {
	f.Where(p.Field(cloudfile.FieldSize))
}

// WhereFileType applies the entql uint8 predicate on the file_type field.
func (f *CloudFileFilter) WhereFileType(p entql.Uint8P) {
	f.Where(p.Field(cloudfile.FieldFileType))
}

// WhereUserID applies the entql string predicate on the user_id field.
func (f *CloudFileFilter) WhereUserID(p entql.StringP) {
	f.Where(p.Field(cloudfile.FieldUserID))
}

// WhereHasStorageProviders applies a predicate to check if query has an edge storage_providers.
func (f *CloudFileFilter) WhereHasStorageProviders() {
	f.Where(entql.HasEdge("storage_providers"))
}

// WhereHasStorageProvidersWith applies a predicate to check if query has an edge storage_providers with a given conditions (other predicates).
func (f *CloudFileFilter) WhereHasStorageProvidersWith(preds ...predicate.StorageProvider) {
	f.Where(entql.HasEdgeWith("storage_providers", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasTags applies a predicate to check if query has an edge tags.
func (f *CloudFileFilter) WhereHasTags() {
	f.Where(entql.HasEdge("tags"))
}

// WhereHasTagsWith applies a predicate to check if query has an edge tags with a given conditions (other predicates).
func (f *CloudFileFilter) WhereHasTagsWith(preds ...predicate.CloudFileTag) {
	f.Where(entql.HasEdgeWith("tags", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *CloudFileTagQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the CloudFileTagQuery builder.
func (_q *CloudFileTagQuery) Filter() *CloudFileTagFilter {
	return &CloudFileTagFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *CloudFileTagMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the CloudFileTagMutation builder.
func (m *CloudFileTagMutation) Filter() *CloudFileTagFilter {
	return &CloudFileTagFilter{config: m.config, predicateAdder: m}
}

// CloudFileTagFilter provides a generic filtering capability at runtime for CloudFileTagQuery.
type CloudFileTagFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *CloudFileTagFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint64 predicate on the id field.
func (f *CloudFileTagFilter) WhereID(p entql.Uint64P) {
	f.Where(p.Field(cloudfiletag.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *CloudFileTagFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(cloudfiletag.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *CloudFileTagFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(cloudfiletag.FieldUpdatedAt))
}

// WhereStatus applies the entql uint8 predicate on the status field.
func (f *CloudFileTagFilter) WhereStatus(p entql.Uint8P) {
	f.Where(p.Field(cloudfiletag.FieldStatus))
}

// WhereTenantID applies the entql uint64 predicate on the tenant_id field.
func (f *CloudFileTagFilter) WhereTenantID(p entql.Uint64P) {
	f.Where(p.Field(cloudfiletag.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *CloudFileTagFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(cloudfiletag.FieldName))
}

// WhereRemark applies the entql string predicate on the remark field.
func (f *CloudFileTagFilter) WhereRemark(p entql.StringP) {
	f.Where(p.Field(cloudfiletag.FieldRemark))
}

// WhereHasCloudFiles applies a predicate to check if query has an edge cloud_files.
func (f *CloudFileTagFilter) WhereHasCloudFiles() {
	f.Where(entql.HasEdge("cloud_files"))
}

// WhereHasCloudFilesWith applies a predicate to check if query has an edge cloud_files with a given conditions (other predicates).
func (f *CloudFileTagFilter) WhereHasCloudFilesWith(preds ...predicate.CloudFile) {
	f.Where(entql.HasEdgeWith("cloud_files", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *FileQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the FileQuery builder.
func (_q *FileQuery) Filter() *FileFilter {
	return &FileFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *FileMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the FileMutation builder.
func (m *FileMutation) Filter() *FileFilter {
	return &FileFilter{config: m.config, predicateAdder: m}
}

// FileFilter provides a generic filtering capability at runtime for FileQuery.
type FileFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *FileFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint64 predicate on the id field.
func (f *FileFilter) WhereID(p entql.Uint64P) {
	f.Where(p.Field(file.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *FileFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(file.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *FileFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(file.FieldUpdatedAt))
}

// WhereStatus applies the entql uint8 predicate on the status field.
func (f *FileFilter) WhereStatus(p entql.Uint8P) {
	f.Where(p.Field(file.FieldStatus))
}

// WhereTenantID applies the entql uint64 predicate on the tenant_id field.
func (f *FileFilter) WhereTenantID(p entql.Uint64P) {
	f.Where(p.Field(file.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *FileFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(file.FieldName))
}

// WhereFileType applies the entql uint8 predicate on the file_type field.
func (f *FileFilter) WhereFileType(p entql.Uint8P) {
	f.Where(p.Field(file.FieldFileType))
}

// WhereSize applies the entql uint64 predicate on the size field.
func (f *FileFilter) WhereSize(p entql.Uint64P) {
	f.Where(p.Field(file.FieldSize))
}

// WherePath applies the entql string predicate on the path field.
func (f *FileFilter) WherePath(p entql.StringP) {
	f.Where(p.Field(file.FieldPath))
}

// WhereUserID applies the entql string predicate on the user_id field.
func (f *FileFilter) WhereUserID(p entql.StringP) {
	f.Where(p.Field(file.FieldUserID))
}

// WhereMd5 applies the entql string predicate on the md5 field.
func (f *FileFilter) WhereMd5(p entql.StringP) {
	f.Where(p.Field(file.FieldMd5))
}

// WhereHasTags applies a predicate to check if query has an edge tags.
func (f *FileFilter) WhereHasTags() {
	f.Where(entql.HasEdge("tags"))
}

// WhereHasTagsWith applies a predicate to check if query has an edge tags with a given conditions (other predicates).
func (f *FileFilter) WhereHasTagsWith(preds ...predicate.FileTag) {
	f.Where(entql.HasEdgeWith("tags", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *FileTagQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the FileTagQuery builder.
func (_q *FileTagQuery) Filter() *FileTagFilter {
	return &FileTagFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *FileTagMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the FileTagMutation builder.
func (m *FileTagMutation) Filter() *FileTagFilter {
	return &FileTagFilter{config: m.config, predicateAdder: m}
}

// FileTagFilter provides a generic filtering capability at runtime for FileTagQuery.
type FileTagFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *FileTagFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[4].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint64 predicate on the id field.
func (f *FileTagFilter) WhereID(p entql.Uint64P) {
	f.Where(p.Field(filetag.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *FileTagFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(filetag.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *FileTagFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(filetag.FieldUpdatedAt))
}

// WhereStatus applies the entql uint8 predicate on the status field.
func (f *FileTagFilter) WhereStatus(p entql.Uint8P) {
	f.Where(p.Field(filetag.FieldStatus))
}

// WhereTenantID applies the entql uint64 predicate on the tenant_id field.
func (f *FileTagFilter) WhereTenantID(p entql.Uint64P) {
	f.Where(p.Field(filetag.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *FileTagFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(filetag.FieldName))
}

// WhereRemark applies the entql string predicate on the remark field.
func (f *FileTagFilter) WhereRemark(p entql.StringP) {
	f.Where(p.Field(filetag.FieldRemark))
}

// WhereHasFiles applies a predicate to check if query has an edge files.
func (f *FileTagFilter) WhereHasFiles() {
	f.Where(entql.HasEdge("files"))
}

// WhereHasFilesWith applies a predicate to check if query has an edge files with a given conditions (other predicates).
func (f *FileTagFilter) WhereHasFilesWith(preds ...predicate.File) {
	f.Where(entql.HasEdgeWith("files", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *StorageProviderQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the StorageProviderQuery builder.
func (_q *StorageProviderQuery) Filter() *StorageProviderFilter {
	return &StorageProviderFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *StorageProviderMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the StorageProviderMutation builder.
func (m *StorageProviderMutation) Filter() *StorageProviderFilter {
	return &StorageProviderFilter{config: m.config, predicateAdder: m}
}

// StorageProviderFilter provides a generic filtering capability at runtime for StorageProviderQuery.
type StorageProviderFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *StorageProviderFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[5].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint64 predicate on the id field.
func (f *StorageProviderFilter) WhereID(p entql.Uint64P) {
	f.Where(p.Field(storageprovider.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *StorageProviderFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(storageprovider.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *StorageProviderFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(storageprovider.FieldUpdatedAt))
}

// WhereState applies the entql bool predicate on the state field.
func (f *StorageProviderFilter) WhereState(p entql.BoolP) {
	f.Where(p.Field(storageprovider.FieldState))
}

// WhereTenantID applies the entql uint64 predicate on the tenant_id field.
func (f *StorageProviderFilter) WhereTenantID(p entql.Uint64P) {
	f.Where(p.Field(storageprovider.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *StorageProviderFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(storageprovider.FieldName))
}

// WhereBucket applies the entql string predicate on the bucket field.
func (f *StorageProviderFilter) WhereBucket(p entql.StringP) {
	f.Where(p.Field(storageprovider.FieldBucket))
}

// WhereSecretID applies the entql string predicate on the secret_id field.
func (f *StorageProviderFilter) WhereSecretID(p entql.StringP) {
	f.Where(p.Field(storageprovider.FieldSecretID))
}

// WhereSecretKey applies the entql string predicate on the secret_key field.
func (f *StorageProviderFilter) WhereSecretKey(p entql.StringP) {
	f.Where(p.Field(storageprovider.FieldSecretKey))
}

// WhereEndpoint applies the entql string predicate on the endpoint field.
func (f *StorageProviderFilter) WhereEndpoint(p entql.StringP) {
	f.Where(p.Field(storageprovider.FieldEndpoint))
}

// WhereFolder applies the entql string predicate on the folder field.
func (f *StorageProviderFilter) WhereFolder(p entql.StringP) {
	f.Where(p.Field(storageprovider.FieldFolder))
}

// WhereRegion applies the entql string predicate on the region field.
func (f *StorageProviderFilter) WhereRegion(p entql.StringP) {
	f.Where(p.Field(storageprovider.FieldRegion))
}

// WhereIsDefault applies the entql bool predicate on the is_default field.
func (f *StorageProviderFilter) WhereIsDefault(p entql.BoolP) {
	f.Where(p.Field(storageprovider.FieldIsDefault))
}

// WhereUseCdn applies the entql bool predicate on the use_cdn field.
func (f *StorageProviderFilter) WhereUseCdn(p entql.BoolP) {
	f.Where(p.Field(storageprovider.FieldUseCdn))
}

// WhereCdnURL applies the entql string predicate on the cdn_url field.
func (f *StorageProviderFilter) WhereCdnURL(p entql.StringP) {
	f.Where(p.Field(storageprovider.FieldCdnURL))
}

// WhereHasCloudfiles applies a predicate to check if query has an edge cloudfiles.
func (f *StorageProviderFilter) WhereHasCloudfiles() {
	f.Where(entql.HasEdge("cloudfiles"))
}

// WhereHasCloudfilesWith applies a predicate to check if query has an edge cloudfiles with a given conditions (other predicates).
func (f *StorageProviderFilter) WhereHasCloudfilesWith(preds ...predicate.CloudFile) {
	f.Where(entql.HasEdgeWith("cloudfiles", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
