// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilUpdatedAt(value *time.Time) *ApkUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilUpdatedAt(value *time.Time) *ApkUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilUpdatedAt(value *time.Time) *ApkCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilStatus(value *uint8) *ApkUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilStatus(value *uint8) *ApkUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilStatus(value *uint8) *ApkCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilName(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilName(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilName(value *string) *ApkCreate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilVersion(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetVersion(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilVersion(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetVersion(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilVersion(value *string) *ApkCreate {
	if value != nil {
		return _m.SetVersion(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilVersionCode(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetVersionCode(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilVersionCode(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetVersionCode(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilVersionCode(value *string) *ApkCreate {
	if value != nil {
		return _m.SetVersionCode(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilFileID(value *uint64) *ApkUpdate {
	if value != nil {
		return _m.SetFileID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilFileID(value *uint64) *ApkUpdateOne {
	if value != nil {
		return _m.SetFileID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilFileID(value *uint64) *ApkCreate {
	if value != nil {
		return _m.SetFileID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilFileSize(value *uint64) *ApkUpdate {
	if value != nil {
		return _m.SetFileSize(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilFileSize(value *uint64) *ApkUpdateOne {
	if value != nil {
		return _m.SetFileSize(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilFileSize(value *uint64) *ApkCreate {
	if value != nil {
		return _m.SetFileSize(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilFileURL(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetFileURL(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilFileURL(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetFileURL(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilFileURL(value *string) *ApkCreate {
	if value != nil {
		return _m.SetFileURL(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilMd5(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetMd5(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilMd5(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetMd5(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilMd5(value *string) *ApkCreate {
	if value != nil {
		return _m.SetMd5(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilSha1(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetSha1(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilSha1(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetSha1(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilSha1(value *string) *ApkCreate {
	if value != nil {
		return _m.SetSha1(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilSha256(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetSha256(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilSha256(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetSha256(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilSha256(value *string) *ApkCreate {
	if value != nil {
		return _m.SetSha256(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilPackageName(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetPackageName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilPackageName(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetPackageName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilPackageName(value *string) *ApkCreate {
	if value != nil {
		return _m.SetPackageName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilDescription(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetDescription(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilDescription(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetDescription(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilDescription(value *string) *ApkCreate {
	if value != nil {
		return _m.SetDescription(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilUpdateLog(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetUpdateLog(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilUpdateLog(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetUpdateLog(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilUpdateLog(value *string) *ApkCreate {
	if value != nil {
		return _m.SetUpdateLog(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilIsForceUpdate(value *bool) *ApkUpdate {
	if value != nil {
		return _m.SetIsForceUpdate(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilIsForceUpdate(value *bool) *ApkUpdateOne {
	if value != nil {
		return _m.SetIsForceUpdate(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilIsForceUpdate(value *bool) *ApkCreate {
	if value != nil {
		return _m.SetIsForceUpdate(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilDownloadCount(value *int64) *ApkUpdate {
	if value != nil {
		return _m.SetDownloadCount(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilDownloadCount(value *int64) *ApkUpdateOne {
	if value != nil {
		return _m.SetDownloadCount(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilDownloadCount(value *int64) *ApkCreate {
	if value != nil {
		return _m.SetDownloadCount(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdate) SetNotNilCategory(value *string) *ApkUpdate {
	if value != nil {
		return _m.SetCategory(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkUpdateOne) SetNotNilCategory(value *string) *ApkUpdateOne {
	if value != nil {
		return _m.SetCategory(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApkCreate) SetNotNilCategory(value *string) *ApkCreate {
	if value != nil {
		return _m.SetCategory(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdate) SetNotNilUpdatedAt(value *time.Time) *CloudFileUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdateOne) SetNotNilUpdatedAt(value *time.Time) *CloudFileUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileCreate) SetNotNilUpdatedAt(value *time.Time) *CloudFileCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdate) SetNotNilState(value *bool) *CloudFileUpdate {
	if value != nil {
		return _m.SetState(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdateOne) SetNotNilState(value *bool) *CloudFileUpdateOne {
	if value != nil {
		return _m.SetState(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileCreate) SetNotNilState(value *bool) *CloudFileCreate {
	if value != nil {
		return _m.SetState(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdate) SetNotNilName(value *string) *CloudFileUpdate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdateOne) SetNotNilName(value *string) *CloudFileUpdateOne {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileCreate) SetNotNilName(value *string) *CloudFileCreate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdate) SetNotNilURL(value *string) *CloudFileUpdate {
	if value != nil {
		return _m.SetURL(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdateOne) SetNotNilURL(value *string) *CloudFileUpdateOne {
	if value != nil {
		return _m.SetURL(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileCreate) SetNotNilURL(value *string) *CloudFileCreate {
	if value != nil {
		return _m.SetURL(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdate) SetNotNilSize(value *uint64) *CloudFileUpdate {
	if value != nil {
		return _m.SetSize(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdateOne) SetNotNilSize(value *uint64) *CloudFileUpdateOne {
	if value != nil {
		return _m.SetSize(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileCreate) SetNotNilSize(value *uint64) *CloudFileCreate {
	if value != nil {
		return _m.SetSize(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdate) SetNotNilFileType(value *uint8) *CloudFileUpdate {
	if value != nil {
		return _m.SetFileType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdateOne) SetNotNilFileType(value *uint8) *CloudFileUpdateOne {
	if value != nil {
		return _m.SetFileType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileCreate) SetNotNilFileType(value *uint8) *CloudFileCreate {
	if value != nil {
		return _m.SetFileType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdate) SetNotNilUserID(value *string) *CloudFileUpdate {
	if value != nil {
		return _m.SetUserID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileUpdateOne) SetNotNilUserID(value *string) *CloudFileUpdateOne {
	if value != nil {
		return _m.SetUserID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileCreate) SetNotNilUserID(value *string) *CloudFileCreate {
	if value != nil {
		return _m.SetUserID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagUpdate) SetNotNilUpdatedAt(value *time.Time) *CloudFileTagUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagUpdateOne) SetNotNilUpdatedAt(value *time.Time) *CloudFileTagUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagCreate) SetNotNilUpdatedAt(value *time.Time) *CloudFileTagCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagUpdate) SetNotNilStatus(value *uint8) *CloudFileTagUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagUpdateOne) SetNotNilStatus(value *uint8) *CloudFileTagUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagCreate) SetNotNilStatus(value *uint8) *CloudFileTagCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagUpdate) SetNotNilName(value *string) *CloudFileTagUpdate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagUpdateOne) SetNotNilName(value *string) *CloudFileTagUpdateOne {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagCreate) SetNotNilName(value *string) *CloudFileTagCreate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagUpdate) SetNotNilRemark(value *string) *CloudFileTagUpdate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagUpdateOne) SetNotNilRemark(value *string) *CloudFileTagUpdateOne {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CloudFileTagCreate) SetNotNilRemark(value *string) *CloudFileTagCreate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdate) SetNotNilUpdatedAt(value *time.Time) *FileUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdateOne) SetNotNilUpdatedAt(value *time.Time) *FileUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileCreate) SetNotNilUpdatedAt(value *time.Time) *FileCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdate) SetNotNilStatus(value *uint8) *FileUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdateOne) SetNotNilStatus(value *uint8) *FileUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileCreate) SetNotNilStatus(value *uint8) *FileCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdate) SetNotNilName(value *string) *FileUpdate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdateOne) SetNotNilName(value *string) *FileUpdateOne {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileCreate) SetNotNilName(value *string) *FileCreate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdate) SetNotNilFileType(value *uint8) *FileUpdate {
	if value != nil {
		return _m.SetFileType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdateOne) SetNotNilFileType(value *uint8) *FileUpdateOne {
	if value != nil {
		return _m.SetFileType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileCreate) SetNotNilFileType(value *uint8) *FileCreate {
	if value != nil {
		return _m.SetFileType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdate) SetNotNilSize(value *uint64) *FileUpdate {
	if value != nil {
		return _m.SetSize(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdateOne) SetNotNilSize(value *uint64) *FileUpdateOne {
	if value != nil {
		return _m.SetSize(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileCreate) SetNotNilSize(value *uint64) *FileCreate {
	if value != nil {
		return _m.SetSize(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdate) SetNotNilPath(value *string) *FileUpdate {
	if value != nil {
		return _m.SetPath(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdateOne) SetNotNilPath(value *string) *FileUpdateOne {
	if value != nil {
		return _m.SetPath(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileCreate) SetNotNilPath(value *string) *FileCreate {
	if value != nil {
		return _m.SetPath(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdate) SetNotNilUserID(value *string) *FileUpdate {
	if value != nil {
		return _m.SetUserID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdateOne) SetNotNilUserID(value *string) *FileUpdateOne {
	if value != nil {
		return _m.SetUserID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileCreate) SetNotNilUserID(value *string) *FileCreate {
	if value != nil {
		return _m.SetUserID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdate) SetNotNilMd5(value *string) *FileUpdate {
	if value != nil {
		return _m.SetMd5(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileUpdateOne) SetNotNilMd5(value *string) *FileUpdateOne {
	if value != nil {
		return _m.SetMd5(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileCreate) SetNotNilMd5(value *string) *FileCreate {
	if value != nil {
		return _m.SetMd5(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagUpdate) SetNotNilUpdatedAt(value *time.Time) *FileTagUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagUpdateOne) SetNotNilUpdatedAt(value *time.Time) *FileTagUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagCreate) SetNotNilUpdatedAt(value *time.Time) *FileTagCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagUpdate) SetNotNilStatus(value *uint8) *FileTagUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagUpdateOne) SetNotNilStatus(value *uint8) *FileTagUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagCreate) SetNotNilStatus(value *uint8) *FileTagCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagUpdate) SetNotNilName(value *string) *FileTagUpdate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagUpdateOne) SetNotNilName(value *string) *FileTagUpdateOne {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagCreate) SetNotNilName(value *string) *FileTagCreate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagUpdate) SetNotNilRemark(value *string) *FileTagUpdate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagUpdateOne) SetNotNilRemark(value *string) *FileTagUpdateOne {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *FileTagCreate) SetNotNilRemark(value *string) *FileTagCreate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilUpdatedAt(value *time.Time) *StorageProviderUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilUpdatedAt(value *time.Time) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilUpdatedAt(value *time.Time) *StorageProviderCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilState(value *bool) *StorageProviderUpdate {
	if value != nil {
		return _m.SetState(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilState(value *bool) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetState(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilState(value *bool) *StorageProviderCreate {
	if value != nil {
		return _m.SetState(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilName(value *string) *StorageProviderUpdate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilName(value *string) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilName(value *string) *StorageProviderCreate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilBucket(value *string) *StorageProviderUpdate {
	if value != nil {
		return _m.SetBucket(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilBucket(value *string) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetBucket(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilBucket(value *string) *StorageProviderCreate {
	if value != nil {
		return _m.SetBucket(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilSecretID(value *string) *StorageProviderUpdate {
	if value != nil {
		return _m.SetSecretID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilSecretID(value *string) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetSecretID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilSecretID(value *string) *StorageProviderCreate {
	if value != nil {
		return _m.SetSecretID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilSecretKey(value *string) *StorageProviderUpdate {
	if value != nil {
		return _m.SetSecretKey(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilSecretKey(value *string) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetSecretKey(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilSecretKey(value *string) *StorageProviderCreate {
	if value != nil {
		return _m.SetSecretKey(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilEndpoint(value *string) *StorageProviderUpdate {
	if value != nil {
		return _m.SetEndpoint(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilEndpoint(value *string) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetEndpoint(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilEndpoint(value *string) *StorageProviderCreate {
	if value != nil {
		return _m.SetEndpoint(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilFolder(value *string) *StorageProviderUpdate {
	if value != nil {
		return _m.SetFolder(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilFolder(value *string) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetFolder(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilFolder(value *string) *StorageProviderCreate {
	if value != nil {
		return _m.SetFolder(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilRegion(value *string) *StorageProviderUpdate {
	if value != nil {
		return _m.SetRegion(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilRegion(value *string) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetRegion(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilRegion(value *string) *StorageProviderCreate {
	if value != nil {
		return _m.SetRegion(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilIsDefault(value *bool) *StorageProviderUpdate {
	if value != nil {
		return _m.SetIsDefault(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilIsDefault(value *bool) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetIsDefault(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilIsDefault(value *bool) *StorageProviderCreate {
	if value != nil {
		return _m.SetIsDefault(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilUseCdn(value *bool) *StorageProviderUpdate {
	if value != nil {
		return _m.SetUseCdn(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilUseCdn(value *bool) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetUseCdn(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilUseCdn(value *bool) *StorageProviderCreate {
	if value != nil {
		return _m.SetUseCdn(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdate) SetNotNilCdnURL(value *string) *StorageProviderUpdate {
	if value != nil {
		return _m.SetCdnURL(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderUpdateOne) SetNotNilCdnURL(value *string) *StorageProviderUpdateOne {
	if value != nil {
		return _m.SetCdnURL(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *StorageProviderCreate) SetNotNilCdnURL(value *string) *StorageProviderCreate {
	if value != nil {
		return _m.SetCdnURL(*value)
	}
	return _m
}
