// Code generated by ent, DO NOT EDIT.

package apk

import (
	"mingyang-admin-simple-admin-file/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldUpdatedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v uint8) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldStatus, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldTenantID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldName, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldVersion, v))
}

// VersionCode applies equality check predicate on the "version_code" field. It's identical to VersionCodeEQ.
func VersionCode(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldVersionCode, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldFileSize, v))
}

// FileID applies equality check predicate on the "file_id" field. It's identical to FileIDEQ.
func FileID(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldFileID, v))
}

// FilePath applies equality check predicate on the "file_path" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldFilePath, v))
}

// Md5 applies equality check predicate on the "md5" field. It's identical to Md5EQ.
func Md5(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldMd5, v))
}

// Sha1 applies equality check predicate on the "sha1" field. It's identical to Sha1EQ.
func Sha1(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldSha1, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldSha256, v))
}

// PackageName applies equality check predicate on the "package_name" field. It's identical to PackageNameEQ.
func PackageName(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldPackageName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldDescription, v))
}

// UpdateLog applies equality check predicate on the "update_log" field. It's identical to UpdateLogEQ.
func UpdateLog(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldUpdateLog, v))
}

// IsForceUpdate applies equality check predicate on the "is_force_update" field. It's identical to IsForceUpdateEQ.
func IsForceUpdate(v bool) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldIsForceUpdate, v))
}

// DownloadCount applies equality check predicate on the "download_count" field. It's identical to DownloadCountEQ.
func DownloadCount(v int64) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldDownloadCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v uint8) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v uint8) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...uint8) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...uint8) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v uint8) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v uint8) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v uint8) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v uint8) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.Apk {
	return predicate.Apk(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.Apk {
	return predicate.Apk(sql.FieldNotNull(FieldStatus))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint64) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint64) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldTenantID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldName, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldVersion, v))
}

// VersionCodeEQ applies the EQ predicate on the "version_code" field.
func VersionCodeEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldVersionCode, v))
}

// VersionCodeNEQ applies the NEQ predicate on the "version_code" field.
func VersionCodeNEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldVersionCode, v))
}

// VersionCodeIn applies the In predicate on the "version_code" field.
func VersionCodeIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldVersionCode, vs...))
}

// VersionCodeNotIn applies the NotIn predicate on the "version_code" field.
func VersionCodeNotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldVersionCode, vs...))
}

// VersionCodeGT applies the GT predicate on the "version_code" field.
func VersionCodeGT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldVersionCode, v))
}

// VersionCodeGTE applies the GTE predicate on the "version_code" field.
func VersionCodeGTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldVersionCode, v))
}

// VersionCodeLT applies the LT predicate on the "version_code" field.
func VersionCodeLT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldVersionCode, v))
}

// VersionCodeLTE applies the LTE predicate on the "version_code" field.
func VersionCodeLTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldVersionCode, v))
}

// VersionCodeContains applies the Contains predicate on the "version_code" field.
func VersionCodeContains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldVersionCode, v))
}

// VersionCodeHasPrefix applies the HasPrefix predicate on the "version_code" field.
func VersionCodeHasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldVersionCode, v))
}

// VersionCodeHasSuffix applies the HasSuffix predicate on the "version_code" field.
func VersionCodeHasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldVersionCode, v))
}

// VersionCodeEqualFold applies the EqualFold predicate on the "version_code" field.
func VersionCodeEqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldVersionCode, v))
}

// VersionCodeContainsFold applies the ContainsFold predicate on the "version_code" field.
func VersionCodeContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldVersionCode, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...uint64) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...uint64) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v uint64) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldFileSize, v))
}

// FileIDEQ applies the EQ predicate on the "file_id" field.
func FileIDEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldFileID, v))
}

// FileIDNEQ applies the NEQ predicate on the "file_id" field.
func FileIDNEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldFileID, v))
}

// FileIDIn applies the In predicate on the "file_id" field.
func FileIDIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldFileID, vs...))
}

// FileIDNotIn applies the NotIn predicate on the "file_id" field.
func FileIDNotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldFileID, vs...))
}

// FileIDGT applies the GT predicate on the "file_id" field.
func FileIDGT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldFileID, v))
}

// FileIDGTE applies the GTE predicate on the "file_id" field.
func FileIDGTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldFileID, v))
}

// FileIDLT applies the LT predicate on the "file_id" field.
func FileIDLT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldFileID, v))
}

// FileIDLTE applies the LTE predicate on the "file_id" field.
func FileIDLTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldFileID, v))
}

// FileIDContains applies the Contains predicate on the "file_id" field.
func FileIDContains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldFileID, v))
}

// FileIDHasPrefix applies the HasPrefix predicate on the "file_id" field.
func FileIDHasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldFileID, v))
}

// FileIDHasSuffix applies the HasSuffix predicate on the "file_id" field.
func FileIDHasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldFileID, v))
}

// FileIDEqualFold applies the EqualFold predicate on the "file_id" field.
func FileIDEqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldFileID, v))
}

// FileIDContainsFold applies the ContainsFold predicate on the "file_id" field.
func FileIDContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldFileID, v))
}

// FilePathEQ applies the EQ predicate on the "file_path" field.
func FilePathEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldFilePath, v))
}

// FilePathNEQ applies the NEQ predicate on the "file_path" field.
func FilePathNEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldFilePath, v))
}

// FilePathIn applies the In predicate on the "file_path" field.
func FilePathIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldFilePath, vs...))
}

// FilePathNotIn applies the NotIn predicate on the "file_path" field.
func FilePathNotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldFilePath, vs...))
}

// FilePathGT applies the GT predicate on the "file_path" field.
func FilePathGT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldFilePath, v))
}

// FilePathGTE applies the GTE predicate on the "file_path" field.
func FilePathGTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldFilePath, v))
}

// FilePathLT applies the LT predicate on the "file_path" field.
func FilePathLT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldFilePath, v))
}

// FilePathLTE applies the LTE predicate on the "file_path" field.
func FilePathLTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldFilePath, v))
}

// FilePathContains applies the Contains predicate on the "file_path" field.
func FilePathContains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldFilePath, v))
}

// FilePathHasPrefix applies the HasPrefix predicate on the "file_path" field.
func FilePathHasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldFilePath, v))
}

// FilePathHasSuffix applies the HasSuffix predicate on the "file_path" field.
func FilePathHasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldFilePath, v))
}

// FilePathIsNil applies the IsNil predicate on the "file_path" field.
func FilePathIsNil() predicate.Apk {
	return predicate.Apk(sql.FieldIsNull(FieldFilePath))
}

// FilePathNotNil applies the NotNil predicate on the "file_path" field.
func FilePathNotNil() predicate.Apk {
	return predicate.Apk(sql.FieldNotNull(FieldFilePath))
}

// FilePathEqualFold applies the EqualFold predicate on the "file_path" field.
func FilePathEqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldFilePath, v))
}

// FilePathContainsFold applies the ContainsFold predicate on the "file_path" field.
func FilePathContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldFilePath, v))
}

// Md5EQ applies the EQ predicate on the "md5" field.
func Md5EQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldMd5, v))
}

// Md5NEQ applies the NEQ predicate on the "md5" field.
func Md5NEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldMd5, v))
}

// Md5In applies the In predicate on the "md5" field.
func Md5In(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldMd5, vs...))
}

// Md5NotIn applies the NotIn predicate on the "md5" field.
func Md5NotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldMd5, vs...))
}

// Md5GT applies the GT predicate on the "md5" field.
func Md5GT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldMd5, v))
}

// Md5GTE applies the GTE predicate on the "md5" field.
func Md5GTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldMd5, v))
}

// Md5LT applies the LT predicate on the "md5" field.
func Md5LT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldMd5, v))
}

// Md5LTE applies the LTE predicate on the "md5" field.
func Md5LTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldMd5, v))
}

// Md5Contains applies the Contains predicate on the "md5" field.
func Md5Contains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldMd5, v))
}

// Md5HasPrefix applies the HasPrefix predicate on the "md5" field.
func Md5HasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldMd5, v))
}

// Md5HasSuffix applies the HasSuffix predicate on the "md5" field.
func Md5HasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldMd5, v))
}

// Md5IsNil applies the IsNil predicate on the "md5" field.
func Md5IsNil() predicate.Apk {
	return predicate.Apk(sql.FieldIsNull(FieldMd5))
}

// Md5NotNil applies the NotNil predicate on the "md5" field.
func Md5NotNil() predicate.Apk {
	return predicate.Apk(sql.FieldNotNull(FieldMd5))
}

// Md5EqualFold applies the EqualFold predicate on the "md5" field.
func Md5EqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldMd5, v))
}

// Md5ContainsFold applies the ContainsFold predicate on the "md5" field.
func Md5ContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldMd5, v))
}

// Sha1EQ applies the EQ predicate on the "sha1" field.
func Sha1EQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldSha1, v))
}

// Sha1NEQ applies the NEQ predicate on the "sha1" field.
func Sha1NEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldSha1, v))
}

// Sha1In applies the In predicate on the "sha1" field.
func Sha1In(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldSha1, vs...))
}

// Sha1NotIn applies the NotIn predicate on the "sha1" field.
func Sha1NotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldSha1, vs...))
}

// Sha1GT applies the GT predicate on the "sha1" field.
func Sha1GT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldSha1, v))
}

// Sha1GTE applies the GTE predicate on the "sha1" field.
func Sha1GTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldSha1, v))
}

// Sha1LT applies the LT predicate on the "sha1" field.
func Sha1LT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldSha1, v))
}

// Sha1LTE applies the LTE predicate on the "sha1" field.
func Sha1LTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldSha1, v))
}

// Sha1Contains applies the Contains predicate on the "sha1" field.
func Sha1Contains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldSha1, v))
}

// Sha1HasPrefix applies the HasPrefix predicate on the "sha1" field.
func Sha1HasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldSha1, v))
}

// Sha1HasSuffix applies the HasSuffix predicate on the "sha1" field.
func Sha1HasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldSha1, v))
}

// Sha1IsNil applies the IsNil predicate on the "sha1" field.
func Sha1IsNil() predicate.Apk {
	return predicate.Apk(sql.FieldIsNull(FieldSha1))
}

// Sha1NotNil applies the NotNil predicate on the "sha1" field.
func Sha1NotNil() predicate.Apk {
	return predicate.Apk(sql.FieldNotNull(FieldSha1))
}

// Sha1EqualFold applies the EqualFold predicate on the "sha1" field.
func Sha1EqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldSha1, v))
}

// Sha1ContainsFold applies the ContainsFold predicate on the "sha1" field.
func Sha1ContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldSha1, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256IsNil applies the IsNil predicate on the "sha256" field.
func Sha256IsNil() predicate.Apk {
	return predicate.Apk(sql.FieldIsNull(FieldSha256))
}

// Sha256NotNil applies the NotNil predicate on the "sha256" field.
func Sha256NotNil() predicate.Apk {
	return predicate.Apk(sql.FieldNotNull(FieldSha256))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldSha256, v))
}

// PackageNameEQ applies the EQ predicate on the "package_name" field.
func PackageNameEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldPackageName, v))
}

// PackageNameNEQ applies the NEQ predicate on the "package_name" field.
func PackageNameNEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldPackageName, v))
}

// PackageNameIn applies the In predicate on the "package_name" field.
func PackageNameIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldPackageName, vs...))
}

// PackageNameNotIn applies the NotIn predicate on the "package_name" field.
func PackageNameNotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldPackageName, vs...))
}

// PackageNameGT applies the GT predicate on the "package_name" field.
func PackageNameGT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldPackageName, v))
}

// PackageNameGTE applies the GTE predicate on the "package_name" field.
func PackageNameGTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldPackageName, v))
}

// PackageNameLT applies the LT predicate on the "package_name" field.
func PackageNameLT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldPackageName, v))
}

// PackageNameLTE applies the LTE predicate on the "package_name" field.
func PackageNameLTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldPackageName, v))
}

// PackageNameContains applies the Contains predicate on the "package_name" field.
func PackageNameContains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldPackageName, v))
}

// PackageNameHasPrefix applies the HasPrefix predicate on the "package_name" field.
func PackageNameHasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldPackageName, v))
}

// PackageNameHasSuffix applies the HasSuffix predicate on the "package_name" field.
func PackageNameHasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldPackageName, v))
}

// PackageNameIsNil applies the IsNil predicate on the "package_name" field.
func PackageNameIsNil() predicate.Apk {
	return predicate.Apk(sql.FieldIsNull(FieldPackageName))
}

// PackageNameNotNil applies the NotNil predicate on the "package_name" field.
func PackageNameNotNil() predicate.Apk {
	return predicate.Apk(sql.FieldNotNull(FieldPackageName))
}

// PackageNameEqualFold applies the EqualFold predicate on the "package_name" field.
func PackageNameEqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldPackageName, v))
}

// PackageNameContainsFold applies the ContainsFold predicate on the "package_name" field.
func PackageNameContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldPackageName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Apk {
	return predicate.Apk(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Apk {
	return predicate.Apk(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldDescription, v))
}

// UpdateLogEQ applies the EQ predicate on the "update_log" field.
func UpdateLogEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldUpdateLog, v))
}

// UpdateLogNEQ applies the NEQ predicate on the "update_log" field.
func UpdateLogNEQ(v string) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldUpdateLog, v))
}

// UpdateLogIn applies the In predicate on the "update_log" field.
func UpdateLogIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldUpdateLog, vs...))
}

// UpdateLogNotIn applies the NotIn predicate on the "update_log" field.
func UpdateLogNotIn(vs ...string) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldUpdateLog, vs...))
}

// UpdateLogGT applies the GT predicate on the "update_log" field.
func UpdateLogGT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldUpdateLog, v))
}

// UpdateLogGTE applies the GTE predicate on the "update_log" field.
func UpdateLogGTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldUpdateLog, v))
}

// UpdateLogLT applies the LT predicate on the "update_log" field.
func UpdateLogLT(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldUpdateLog, v))
}

// UpdateLogLTE applies the LTE predicate on the "update_log" field.
func UpdateLogLTE(v string) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldUpdateLog, v))
}

// UpdateLogContains applies the Contains predicate on the "update_log" field.
func UpdateLogContains(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContains(FieldUpdateLog, v))
}

// UpdateLogHasPrefix applies the HasPrefix predicate on the "update_log" field.
func UpdateLogHasPrefix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasPrefix(FieldUpdateLog, v))
}

// UpdateLogHasSuffix applies the HasSuffix predicate on the "update_log" field.
func UpdateLogHasSuffix(v string) predicate.Apk {
	return predicate.Apk(sql.FieldHasSuffix(FieldUpdateLog, v))
}

// UpdateLogIsNil applies the IsNil predicate on the "update_log" field.
func UpdateLogIsNil() predicate.Apk {
	return predicate.Apk(sql.FieldIsNull(FieldUpdateLog))
}

// UpdateLogNotNil applies the NotNil predicate on the "update_log" field.
func UpdateLogNotNil() predicate.Apk {
	return predicate.Apk(sql.FieldNotNull(FieldUpdateLog))
}

// UpdateLogEqualFold applies the EqualFold predicate on the "update_log" field.
func UpdateLogEqualFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldEqualFold(FieldUpdateLog, v))
}

// UpdateLogContainsFold applies the ContainsFold predicate on the "update_log" field.
func UpdateLogContainsFold(v string) predicate.Apk {
	return predicate.Apk(sql.FieldContainsFold(FieldUpdateLog, v))
}

// IsForceUpdateEQ applies the EQ predicate on the "is_force_update" field.
func IsForceUpdateEQ(v bool) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldIsForceUpdate, v))
}

// IsForceUpdateNEQ applies the NEQ predicate on the "is_force_update" field.
func IsForceUpdateNEQ(v bool) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldIsForceUpdate, v))
}

// DownloadCountEQ applies the EQ predicate on the "download_count" field.
func DownloadCountEQ(v int64) predicate.Apk {
	return predicate.Apk(sql.FieldEQ(FieldDownloadCount, v))
}

// DownloadCountNEQ applies the NEQ predicate on the "download_count" field.
func DownloadCountNEQ(v int64) predicate.Apk {
	return predicate.Apk(sql.FieldNEQ(FieldDownloadCount, v))
}

// DownloadCountIn applies the In predicate on the "download_count" field.
func DownloadCountIn(vs ...int64) predicate.Apk {
	return predicate.Apk(sql.FieldIn(FieldDownloadCount, vs...))
}

// DownloadCountNotIn applies the NotIn predicate on the "download_count" field.
func DownloadCountNotIn(vs ...int64) predicate.Apk {
	return predicate.Apk(sql.FieldNotIn(FieldDownloadCount, vs...))
}

// DownloadCountGT applies the GT predicate on the "download_count" field.
func DownloadCountGT(v int64) predicate.Apk {
	return predicate.Apk(sql.FieldGT(FieldDownloadCount, v))
}

// DownloadCountGTE applies the GTE predicate on the "download_count" field.
func DownloadCountGTE(v int64) predicate.Apk {
	return predicate.Apk(sql.FieldGTE(FieldDownloadCount, v))
}

// DownloadCountLT applies the LT predicate on the "download_count" field.
func DownloadCountLT(v int64) predicate.Apk {
	return predicate.Apk(sql.FieldLT(FieldDownloadCount, v))
}

// DownloadCountLTE applies the LTE predicate on the "download_count" field.
func DownloadCountLTE(v int64) predicate.Apk {
	return predicate.Apk(sql.FieldLTE(FieldDownloadCount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Apk) predicate.Apk {
	return predicate.Apk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Apk) predicate.Apk {
	return predicate.Apk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Apk) predicate.Apk {
	return predicate.Apk(sql.NotPredicates(p))
}
